### ISSUE TITLE
Promise style 

### ISSUE THREAD

**Issue by C-E-Rios** [BookingBug/javascript-styleguide#1]
Thought we could test how git issues will serve as a place to discuss style options and what people prefer. 

Lifted this from a discussion that was started on the slack channel by James. 

Lehgo!

```javascript
function somethingAsync() {
    return new Promise((resolve, reject) => {
        // fetch some stuff from somewhere
    });
}

function anotherAsync(data) {
    return new Promise((resolve, reject) => {
        // do something with data passed in
    });
}

// not nice
somethingAsync().then(stuff => {
    // handle data
    console.log(stuff);
}, (err) => {
    console.log(err);
});

// very not nice
somethingAsync().then(stuff => {
    anotherAsync(stuff).then(moreStuff => {
        console.log(moreStuff);
    }, err => {
        // error handling for nested promise
        console.log(err);
    });
}, (err) => {
    // error handling for first promise
    console.log(err);
});


// nicer
somethingAsync
    .then((stuff) => {
        console.log(stuff);
    })
    .catch((err) => {
        console.log(err);
    })
    .finally(() => {
        // optional clean up
    });

// allows for chaining multiple promises with just 1 error handler.
somethingAsync
    .then(anotherAsync)
    .then((moreStuff) => {
        // result of second promise
        console.log(moreStuff);
    })
    .catch((err) => {
        // catch rejections from both promises in the same block
    });
    
// real life 
halClient
    .$post(`${apiUrl}/api/v1/login/admin_sso/${companyId}`, {}, data)
    .then((login) => {
        const params = {auth_token: login.auth_token};
        login
            .$get('administrator', params)
            .then((admin) => {
                defer.resolve(admin);
            })
            .catch((err) => {
                defer.reject(err);
            });
    })
    .catch((err) => {
        defer.reject(err);
    });
```

**Comment by PiotrSiatkowski** [comment]
I like this style very much. Neat and clean. Readable. But why do you want to handle promise inside a promise in real life example? Can we also check if we can turn syntax colours on?

**Comment by jthomas1** [comment]
I think for the real life example you want to do this:

```javascript 
halClient
    .$post(`${apiUrl}/api/v1/login/admin_sso/${companyId}`, {}, data)
    .then((login) => {
        const params = { auth_token: login.auth_token };
        return login.$get('administrator', params)
    })
    .then((admin) => {
        defer.resolve(admin);
    })
    .catch((err) => {
        // all errors handled in one place
        defer.reject(err);
    });
 ```

**Comment by C-E-Rios** [comment]
ding ding ding @jthomas1  wins!

@victorjeman will get your cookie ready

**Comment by jthomas1** [comment]
N.B. to get the syntax highlighting https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by victorjeman** [comment]
So how we guys could proceed with changing something like this in the whole application? Do you have some specific steps? Is this something done by a single person, or this is something done by every person when he gets something like this in his way ?

**Comment by jthomas1** [comment]
@victorjeman The idea is that we agree on a style that we want to use going forward for all new stuff and when you're doing some work in some existing code that has the old syntax you can tidy it up as you go along.

Generally the code review process is for raising stylistic points such as this as the unit tests etc are for catching bugs and unexpected behaviour

**Comment by jthomas1** [comment]
As we talked about the other day in our retro I do wonder how much weird looking code is the result of the coffee -> es6 conversion.

**Comment by C-E-Rios** [comment]
We should all follow the boy scout principle.

> The Boy Scouts have a rule: "Always leave the campground cleaner than you found it." If you find a mess on the ground, you clean it up regardless of who might have made the mess. You intentionally improve the environment for the next group of campers. Actually the original form of that rule, written by Robert Stephenson Smyth Baden-Powell, the father of scouting, was "Try and leave this world a little better than you found it."

> What if we followed a similar rule in our code: "Always check a module in cleaner than when you checked it out." No matter who the original author was, what if we always made some effort, no matter how small, to improve the module. What would be the result?

@victorjeman

**Comment by C-E-Rios** [comment]
Also probably worth mentioning a few things that are implied, that we should all be on the same page for. Not specifically to do with promises but..

Argument always has brackets.

    .then((login) => {
        const params = { auth_token: login.auth_token };
        return login.$get('administrator', params)
    })

Prefer const over let

    const params = { auth_token: login.auth_token };
    return login.$get('administrator', params)

Always multiple line / Avoid single line return

    .catch((err) => {
        defer.reject(err);
    });

What do people think?

**Comment by ParanormalCoder** [comment]
Well, simply the nice one:

```
somethingAsync
    .then(anotherAsync)
...
```
is equal to:
```
somethingAsync
    .then(param=>anotherAsync(param))
...
```

So, the view about having:
```
somethingAsync
    .then(param=>{anotherAsync(param)})
...
```

is completely a common JS mistake from the beginning with Promises.

**Comment by jthomas1** [comment]
My personal preference is to drop the parens around a single parameter function (generally anywhere not just promises).

```javascript
myPromise().then(stuff => {
    doSome(stuff);
})
```

Pros: 
* the specification says you don't need them
* less typing
* looks neater

Cons:
?

**Comment by flaviotulino** [comment]
The only remark I have is about not mixing Promise and $q library.
To be honest, we should get rid of $q.

@jthomas1 usually I follow the specification, and I agree with the parens-less syntax for a single param.

**Comment by jthomas1** [comment]
Yeh when I wrote the original jsfiddle I just used Promise cos I've been using it in node all the time so my hands were on auto pilot :D 

Sadly Promise is not supported in Internet Explorer at all :'( 

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise

**Comment by flaviotulino** [comment]
@jthomas1 babel has a polyfill for this. I've always used Promise commercially and I've never had problems.

**Comment by PiotrSiatkowski** [comment]
$q is is still useful for example for $q,all function. For requests, we probably should be using $http or wrappers around it.

I think one liner are good options with => and some transformations. But in the case of promises, we should always be prepared for chaining that's why I think we should always start a new line.

I think we should open a separate issue on () around parameters in arrow expressions.

I agree with the scout rule. That's why we are working on guidelines to a have an objective measure what 'better' means.

**Comment by flaviotulino** [comment]
@PiotrSiatkowski $q.all can be replaced by Promise.all. Did you mean this?

**Comment by jthomas1** [comment]
@flaviotulino Nice, well in that case since Babel polyfills everything I am very much in favour of dropping $q for Promise instead.

**Comment by C-E-Rios** [comment]
I think moving to Promise would be a good idea. Great shout @flaviotulino. 

Can you provide an example using the code below?


```javascript
const defer = $q.defer();

halClient
    .$post(`${apiUrl}/api/v1/login/admin_sso/${companyId}`, {}, data)
    .then((login) => {
        const params = { auth_token: login.auth_token };
        return login.$get('administrator', params)
    })
    .then((admin) => {
        defer.resolve(admin);
    })
    .catch((err) => {
        defer.reject(err);
    });

return defer.promise;

```

**Comment by jthomas1** [comment]
It's almost exactly the same except instead of creating a defer object you rerturn a `new Promise((resolve, reject)` which has the handlers injected into the callback you pass into the constructor

```javascript
    return new Promise((resolve, reject) => {
        halClient
            .$post(`${apiUrl}/api/v1/login/admin_sso/${companyId}`, {}, data)
            .then((login) => {
                const params = { auth_token: login.auth_token };
                return login.$get('administrator', params)
            })
            .then(resolve)
            .catch(reject);
    });
```

**Comment by PiotrSiatkowski** [comment]
@flaviotulino Yeah, when nobody is using it, it's easy to forget it exists. You are right, if it has the same functionality it's ok. But can we defer ES6 Promise? Deferring API is not so intuitive but it is useful sometimes when code goes mad.

**Comment by jthomas1** [comment]
Defer is not necessary anymore but if you really wanted to you could do:

```javascript
const myPromise = new Promise((resolve, reject) => {
// blah blah blah
})

return myPromise
```

**Comment by flaviotulino** [comment]
@jthomas1 exactly James.
I'm going to share also a real life example with Promise.all()

**Context**: I was creating a new mapComponent with the new search policies.
**Note**: remember we can now define components versions, and have a "parallel versions".

This is an extract of the code I write in [map component](https://github.com/BookingBug/bookingbug-angular/blob/CORE-2167a/src/core/javascripts/components/map/map.component.js)
We had to fetch 3 resources at once, our API, googlePlaces and googleGeocode.
I created 3 promises and then I used Promise.all([.....]).

```javascript
let searchForText = new Promise((resolve, reject) => {
            this.CompanyService.queryByText(this.BBWidget.company.id, {text: this.query}).then(companies => {
                if (companies.length > 0) {
                    resolve(companies);
                } else {
                    resolve({error: 'NOTHING_FOUND'});
                }
            }, error => {
                resolve({error: error});
            });
        });

        let googlePlaces = new Promise((resolve, reject) => {
            new google.maps.places.PlacesService(this.getCanvas())
                .textSearch({query: this.query, location: searchBounds}, (results, status) => {
                    if (status === 'OK' && results.length > 0) {
                        resolve(results);
                    } else {
                        resolve({error: 'NO_PLACES_FOUND'});
                    }
                });
        });

        let googleGeocode = new Promise((resolve, reject) => {
            new google.maps.Geocoder().geocode({address: this.query}, (results, status) => {
                if (results[0] !== undefined && (results.length > 0 || results[0].partial_match)) {
                    resolve(results);
                } else {
                    resolve({error: 'NOTHING_FOUND'});
                }
            });
        });


        /**
         * Business Logic Here!
         * We decided to trigger all the tree searches at the same time.
         *
         * We search for the company name/description, for a place in Google and for the address in Google.
         *
         * Then we retrieve the coordinates from one of the result, giving a precedence to our result (if any)
         * and then to the google's ones.
         * With these coordinates we search for companies by address
         */
        Promise.all([searchForText, googlePlaces, googleGeocode]).then(values => {

            let [searchForText, googlePlaces, googleGeocode] = values;
            let coordinates = {};

            // All of promise have an error
            if (searchForText.error && googlePlaces.error && googleGeocode.error) {
                return Promise.reject(searchForText.error);
            }

            // A company has been found in our database
            if (searchForText.length > 0) {
                coordinates = {
                    lat: searchForText[0].address.lat,
                    long: searchForText[0].address.long
                };

            } else if (googlePlaces.length > 0) {
                coordinates = {
                    lat: googlePlaces[0].geometry.location.lat(),
                    long: googlePlaces[0].geometry.location.lng()
                };
                this.query = googlePlaces[0].name;

            } else if (googleGeocode.length > 0) {
                coordinates = {
                    lat: googleGeocode[0].geometry.location.lat(),
                    long: googleGeocode[0].geometry.location.lng()
                };
                this.query = this.parseAddressComponents(googleGeocode[0].address_components);

            }

            this.CompanyService.queryByCoords(this.BBWidget.company.id, {coords: coordinates}).then(companies => {

                if (companies.length > 0) {
                    this.showResults(this.sortByDistance(companies, coordinates));
                    this.queryCopy = angular.copy(this.query);
                } else {
                    return Promise.reject('NOTHING_FOUND');
                }
            });
        }).catch(error => {

            this.queryCopy = angular.copy(this.query);
            this.results = [];
            this.clearMarkers();
            this.$timeout(() => {
                this.loader.setLoaded();
            });

            this.AlertService.clear();
        });

    }
```
PS. Sorry for the poor indentation, but GitHub is stupid.

**Comment by jthomas1** [comment]
CORRECTION: `finally()` is only available in $q and bluebird not native Promises yet :(
You can put another `.then` after a `.catch` to pretend we have `finally`

Original comment:
Another point regarding promises that we can make use of is that they have a `.finally()` block available as well for general clean up like disabling loading spinners etc.

**Comment by C-E-Rios** [comment]
So we're agreed:

- Let's phase out `$q`. 
- Use ES6 Promise. 
- Use `.catch` instead of `error` callback. 
- If you need `finally`, use `.then`, after `.catch` for the reasons James explained above. 

I guess this can be the first addition to our Angular Style Guide. Now to decide where that lives? 🤔
