### ISSUE TITLE
Parentheses in arrow expressions.

### ISSUE THREAD

**Issue by PiotrSiatkowski** [BookingBug/javascript-styleguide#2]
Another thing that I think we may not all agree on is parentheses usage in arrow expressions.

For consistency, it is a good thing to use them all the time, but in my opinion for short transformations like
```javascript
list.map(x => x + 1);
```

we should stick to the form above. No return expression, no semicolon, no parentheses.

But what about promises? Promise's callback function is usually complicated and long but the anticipated parameter is well defined (it promise's resolved value). Lack of parentheses is in this case friendly for eyes and more readable in my opinion. What do you think?

**Comment by C-E-Rios** [comment]
I disagree. 

When writing code, I think we should try to always be as clear as possible and if typing more is a consequence of that, so be it. 

```
// Don't mind this
list.map((x) => x + 1);

// Prefer this
list.map((x) => {
    return x + 1;
});

```

Just my two cents. As always happy to go with the majority.

**Comment by jthomas1** [comment]
I just got into a habit of not using them because you don't have to and its easier on the eyes. However if there is a demonstrable negative consequence of not using them then I'm happy to go with it but for now I will continue to fly the flag for no parens :P

**Comment by PiotrSiatkowski** [comment]
The only disadvantage I can think of is consistency. We should work out style on chaining functions too.

Do we want this?
```javascript
elements 
    .map(x => x + 1)
    .filter(x => x > 2)
    .reduce(etc...
```
Or this?
```javascript
elements 
    .map((x) => {
        return x + 1;
    })
    .filter((x) =>{
        return x > 2;
    })
   .etc
```

**Comment by C-E-Rios** [comment]
I see your point @PiotrSiatkowski - Explicit returns do start to look a bit ugly when using that kind of functional approach. For me, always, always parentheses though. It's easier on the eyes ;)

**Comment by flaviotulino** [comment]
For one line statement I use no parens, like @PiotrSiatkowski 's first example.
For multiple lines, brackets and return statement. 
It's just the style I usually follow, what do you think?

**Comment by jthomas1** [comment]
I'm happy to go with the no parens for 1 liners and parens for everything else if that is the consensus. Which is what airbnb are saying already.

**Comment by C-E-Rios** [comment]
Democracy has spoken. I've added the rule. 

`"arrow-parens": [2, "as-needed", { "requireForBlockBody": true }]`

PR for your ref:  https://github.com/BookingBug/bookingbug-angular/pull/952

**Comment by C-E-Rios** [comment]
Prefer to have parentheses in one liners, with one argument. eg:

```javascript
elements 
    .map((x) => x + 1)
    .filter((x) => x > 2)
```

**Comment by C-E-Rios** [comment]
Prefer to have no parentheses in one liners, with one argument. eg:

```javascript
elements 
    .map(x => x + 1)
    .filter(x => x > 2)
```

**Comment by jthomas1** [comment]
Prefer to have no parentheses on any single argument functions eg:

```javascript
promise.then(stuff => {
    console.log(stuff)
})
```

**Comment by bogdansavin** [comment]
I use:
 
elements 
    .map(x => x + 1)
    .filter(x => x > 2)
    .reduce(etc...

but it's not a big deal with () { }

**Comment by C-E-Rios** [comment]
Thanks for voting, those that took part. It's settled. 

Prefer to have no parentheses in one liners, with one argument wins eg:

```javascript
elements 
    .map(x => x + 1)
    .filter(x => x > 2)
```
